import PBO.KONEKSI;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;import java.sql.*;

/**
 *
 * @author Desrita ERNIATI
 * 29/03/2022 10:37
 */
public class MenuUtama extends javax.swing.JFrame {

    Connection konek;
    ResultSet res;
    Statement stat;
    String sql;
    //private Object paSs;
    //private Object uName;

    /**
     * Creates new form MenuUtama
     */
    @SuppressWarnings("static-access")
    public MenuUtama() {
        initComponents();
        KONEKSI Db=new KONEKSI();
        Db.konek();
        konek = db.conn;
        stat = db.stat;    
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jTextField = new javax.swing.JTextField();
        Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("MARKET BY TRIA");

        jLabel2.setText("USERNAME");

        jLabel3.setText("PASSWORD");

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Login)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Login)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
    
// TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
try{
    sql="select*from pengguna where nama='"+userName.getText()+"'AND sandi='"+passWord.getText()+"'";
    res =stat.executeQuery(sql);
    if(res.next()){
       if (userName.getText().equals(res.getString("nama"))&&passWord.getText().equals(res.getString("sandi")))
                {
 //   String uName ="Riyadho";
//}//uName untuk memasukkan username yang bernilai true, sedangkan string yaitu tipe data yang digunakan untuk memasukkan username
//String paSs="202113028";// paSs untuk memasukkan password yang bernilai true, sedangkan string yaitu tipe data untuk memasukkan password
//if(userName.getTextr().equals(uName)&&passWord.getText().equals(paSs)){/*1. if yaitu fungsi percabangan yang apabila password dan username
//                                                                              yang diinputkan benar,maka akan bernilai true sehingga button bisa di klik.
//                                                                         2.  && yaitu untuk membandingkan kebenaran nilai data yang diinput keduanya
//                                                                             harus bernilai benar.
 //                                                                        3.  getText yaitu untuk mengambil teks penginputan
//                                                                         4.  equals yaitu untuk membandingkan dua string yang diinputkan memiliki 
//                                                                             nilai yang true. */
    
MenuUtama Utami= new MenuUtama();/*menukedua sebagai halaman yang ditampilkan ketika kedua string bernilai true
                                      sedangkan dua=new yaitu untuk menunjukkan bahwa dua adalah halaman selanjutnya.*/
Utami.setVisible(true);//setvisible(true) untuk mengatur output supaya bisa ditampilkan
this.setVisible(false);//jika output bernilai salah maka akan tetap di halaman login    
        }
    }else{
        JOptionPane.showMessageDialog(this,"Maaf Anda Melakukan Username Atau Password Salah Sebanyak 1 kali","Message",JOptionPane.INFORMATION_MESSAGE);
         // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed
}catch (HeadlessException | SQLException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
// TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed
    
}
MenuUtama (Exception e){
    JOptionPane.showMessageDialog(this, e.getMessage());
} 

    private static class userName {

        private static String getText() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public userName() {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // MenuYtama=new MenuUtma DESRITA ERNIATI=new MenuUtama)();                new MenuUtama().setVisible(true);
               new MenuUtama().setVisible(true);
            }
        });
    }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
  
        private void If(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    }
}

